dist: trusty
sudo: required
addons:
  apt:
    packages:
      - python-dev

language: go

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - DESTINATION_PATH="https://cloudmethodssa.blob.core.windows.net/cloud-methods-blog"
    - CDN_RESOURCE_GROUP="cloud-methods-rg"
    - CDN_ENDPOINT_NAME="cloud-methods"
    - CDN_PROFILE="cloud-methods-cdn"

install:
  - go get -u -v github.com/spf13/hugo

# Build the website
script:
  - hugo version
  - make deploy

