baseurl = "https://www.cloud-methods.com/"
languageCode = "en-us"
paginate = 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname = "cloud-methods"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-68954351-1"

theme = "hugo-minimalist-theme"

[params]
    site_author = "Lawrence Mulligan"
    site_description = "Microsoft Azure, Kubernetes, DevOps, and other cool stuff"
    location = "Chicago, IL, USA"
    # Link custom assets relative to /static
    avatar = "img/cloud-305461_160.png"
    header_background = "img/scattered-stratus.jpg"
    header_title = "Cloud Methods"
    copyright = "Lawrence Mulligan"
    custom_css = []
    custom_js  = []

[social]
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
    twitter   = "lpmulligan"
    facebook  = ""
    linkedin  = "lpmulligan"
    behance   = ""
    dribbble  = ""
    instagram = ""
    github    = "lpmulligan"
    gplus     = ""
